<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TasksTableSeeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            'Prepare quarterly financial report',
            'Complete client project proposal',
            'Attend project meeting',
            'Review team progress',
            'Prepare marketing materials',
            'Test new software features',
            'Develop new application module',
            'Update project documentation',
            'Coordinate with HR for recruitment',
            'Prepare monthly sales report',
            'Conduct market research',
            'Plan team-building event',
            'Create product demo video',
            'Analyze customer feedback',
            'Prepare budget proposal',
            'Coordinate with vendors',
            'Organize product launch',
            'Create social media posts',
            'Evaluate software performance',
            'Review team KPIs',
            'Prepare training materials',
            'Attend industry conference',
            'Conduct performance reviews',
            'Update company website',
            'Coordinate with legal team',
            'Optimize project workflow',
            'Conduct user experience testing',
            'Prepare annual business plan',
            'Handle customer service inquiries',
            'Update client database',
            'Create email marketing campaign',
            'Manage company event logistics',
            'Conduct competitor analysis',
            'Analyze sales data',
            'Prepare press release',
            'Manage project deadlines',
            'Coordinate team schedule',
            'Track project milestones',
            'Review contract terms',
            'Finalize product packaging design',
            'Attend client meeting',
            'Prepare employee performance report',
            'Manage office supplies inventory',
            'Monitor project budget',
            'Develop customer loyalty program',
            'Assist with employee onboarding',
            'Manage social media accounts',
            'Organize client workshops',
            'Update product catalog',
            'Develop product feature roadmap',
            'Monitor market trends',
            'Manage supplier relationships',
            'Conduct employee surveys',
            'Create website content',
            'Track industry news',
            'Create user guides',
            'Design marketing materials',
            'Provide technical support',
            'Develop internal tools',
            'Maintain product inventory',
            'Attend sales training seminar',
            'Develop strategic partnerships',
            'Organize team meetings',
            'Prepare company newsletter',
            'Plan company budget',
            'Conduct focus group research',
            'Coordinate product testing',
            'Prepare customer satisfaction survey',
            'Analyze customer purchasing patterns',
            'Collaborate with design team',
            'Write product specifications',
            'Test marketing campaigns',
            'Manage company CRM system',
            'Create online surveys',
            'Develop project timeline',
            'Review supplier contracts',
            'Monitor social media performance',
            'Coordinate event sponsorships',
            'Update employee handbook',
            'Plan company growth strategy',
            'Develop sales strategy',
            'Conduct training sessions',
            'Prepare client invoices',
            'Manage IT support requests',
            'Assist with trade show preparations',
            'Prepare investor presentation',
            'Assist with contract negotiations',
            'Create product launch plan',
            'Track project resources',
            'Coordinate team activities',
            'Manage project risks',
            'Assist with employee benefits enrollment',
            'Analyze product pricing strategy',
            'Conduct internal audits',
            'Create promotional videos',
            'Assist with data analysis',
            'Coordinate company partnerships',
            'Prepare product sample packages',
            'Assist with business proposals',
            'Manage client relationships',
            'Create project status reports',
            'Coordinate with finance department',
            'Prepare corporate presentation',
            'Develop business continuity plan',
            'Assist with customer engagement',
            'Review marketing budget',
            'Monitor employee satisfaction',
            'Plan employee recognition program',
            'Assist with product design revisions',
            'Coordinate with IT team for software updates',
            'Conduct project post-mortem',
            'Organize client appreciation events',
            'Prepare vendor contracts',
            'Assist with inventory management',
            'Develop team performance metrics',
            'Prepare product demonstration',
            'Manage email inbox',
            'Assist with public relations efforts',
            'Track employee attendance',
            'Prepare job descriptions',
            'Coordinate employee training',
            'Assist with project closure',
            'Evaluate marketing ROI',
            'Track product returns',
            'Assist with supply chain management',
            'Monitor industry regulations',
            'Develop employee performance plans'
        ];        

        foreach ($tasks as $description) {
            $createdAt = now()->subDays(rand(1, 365));
            $estimatedTime = rand(60, 300);
            $usedTime = rand(0, 500);
            $completedAt = rand(0, 1) ? $createdAt->copy()->addMinutes(rand($estimatedTime, $usedTime)) : null;

            DB::table('tasks')->insert([
                'description' => $description,
                'user_id' => rand(1, 10),
                'estimated_time' => $estimatedTime,
                'used_time' => $usedTime,
                'created_at' => $createdAt,
                'updated_at' => now(),
                'completed_at' => $completedAt,
                'deleted_at' => null,
            ]);
        }
    }
}
